### ISSUE TITLE
[Info] Created a Docker image

### ISSUE THREAD

**Issue by tronyx** [banjo/plex-web#8]
Not an issue, hence the `[Info]` tag, but I just wanted to let you know that I've created a Docker image for this great project:

https://hub.docker.com/r/tronyx/plex-web

Source repo can be found here:

https://github.com/christronyxyocum/docker-plex-web

**Comment by banjo** [comment]
That's great. Thanks! I added the information to the README.

**Comment by tronyx** [comment]
No problem! Just need to figure out a way for triggering auto-builds when you update the application.

**Comment by tronyx** [comment]
Closing this out.
